# https://docs.docker.com/compose/compose-file/

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.17.1
    ports:
      - 5001:5000
    environment:
      - MLFLOW_HOST=0.0.0.0
    command: mlflow server

  mlflow_gateway:
    build:
      context: .
      dockerfile: mlflow_gateway/Dockerfile
    ports:
      - 7001:7000
    environment:
      - MLFLOW_HOST=0.0.0.0
      - MLFLOW_DEPLOYMENTS_CONFIG=/confs/ai_gateway.yaml
      - OPENAI_API_KEY
    env_file:
      - .env
    command: mlflow gateway start --config-path /confs/ai_gateway.yaml --port 7000 --host 0.0.0.0
  
  qdrant:
      image: qdrant/qdrant:latest
      restart: always
      container_name: qdrant
      ports:
        - 6333:6333
        - 6334:6334
      expose:
        - 6333
        - 6334
        - 6335
      configs:
        - source: qdrant_config
          target: /qdrant/config/production.yaml
      volumes:
        - ./qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO      